name: Trigger SailPoint API on CSV Update

on:
  push:
    paths:
      - 'data.csv'  # Watch for changes to the CSV file

jobs:
  trigger-sailpoint:
    runs-on: [self-hosted, Linux, X64]  # Use your runner's labels here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the desired Python version

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          venv/lib/python*/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Process CSV and Save to JSON
      run: |
        source venv/bin/activate
        python process_csv.py

    - name: Send Data to SailPoint
      env:
        SAILPOINT_API_URL: ${{ secrets.SAILPOINT_API_URL }}
        SAILPOINT_AUTH_HEADER: ${{ secrets.SAILPOINT_AUTH_HEADER }}
      run: |
        source venv/bin/activate
        python send_to_sailpoint.py
