name: Trigger Lambda on CSV Update

on:
  push:
    paths:
      - 'data.csv'  # Watch for changes to the CSV file

jobs:
  trigger-lambda:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y jq curl

    - name: Extract the last entry from CSV
      id: extract_last_entry
      run: |
        # Extract the last line from the CSV file
        last_entry=$(tail -n 1 data.csv)
        # Convert to JSON format
        entry_json=$(echo "$last_entry" | jq -R 'split(",") | {name: .[0], email: .[1]}')
        # Save the JSON data to a file
        echo "$entry_json" > last_entry.json

    - name: Retrieve last entry and send to Lambda
      env:
        LAMBDA_FUNCTION_URL: ${{ secrets.LAMBDA_FUNCTION_URL }}
        LAMBDA_FUNCTION_API_KEY: ${{ secrets.LAMBDA_FUNCTION_API_KEY }}
      run: |
        # Read the JSON data from the file
        last_entry=$(cat last_entry.json)

        # Ensure last_entry is a valid JSON
        if [ -z "$last_entry" ] || [ "$last_entry" = "null" ]; then
          echo "No valid last entry found."
          exit 1
        fi

        # Extract name and email
        name=$(echo "$last_entry" | jq -r '.name')
        email=$(echo "$last_entry" | jq -r '.email')

        # Handle null values for name and email
        if [ "$name" = "null" ]; then name=""; fi
        if [ "$email" = "null" ]; then email=""; fi

        # Send the data to the Lambda function
        curl -X POST $LAMBDA_FUNCTION_URL \
          -H "Content-Type: application/json" \
          -H "x-api-key: $LAMBDA_FUNCTION_API_KEY" \
          -d '{"userName": "'"$name"'", "email": "'"$email"'"}'
