name: Trigger Lambda on CSV Update

on:
  push:
    paths:
      - 'data.csv'  # Watch for changes to the CSV file

jobs:
  trigger-lambda:
    runs-on: [self-hosted, Linux, X64]  # Use your runner's labels here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the desired Python version

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install requests

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          venv/lib/python*/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Process CSV and Save to JSON
      run: |
        source venv/bin/activate
        python process_csv.py

    - name: Retrieve last entry and send to Lambda
      env:
        LAMBDA_FUNCTION_URL: ${{ secrets.LAMBDA_FUNCTION_URL }}
        LAMBDA_FUNCTION_API_KEY: ${{ secrets.LAMBDA_FUNCTION_API_KEY }}
      run: |
        source venv/bin/activate
        python -c "
import json
import requests

with open('last_entry.json') as f:
    last_entry = json.load(f)

if not last_entry:
    print('No valid last entry found.')
    exit(1)

name = last_entry.get('name', '')
email = last_entry.get('email', '')

response = requests.post(
    url='${{ secrets.LAMBDA_FUNCTION_URL }}',
    headers={
        'Content-Type': 'application/json',
        'x-api-key': '${{ secrets.LAMBDA_FUNCTION_API_KEY }}'
    },
    json={
        'userName': name,
        'email': email
    }
)
print(response.status_code, response.text)
"
