name: Trigger Lambda on CSV Update

on:
  push:
    paths:
      - 'data.csv'  # Watch for changes to the CSV file

jobs:
  trigger-lambda:
    runs-on: [self-hosted, Linux, X64]  # Use your runner's labels here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install requests

    - name: Process CSV and Save to JSON
      run: python3 process_csv.py

    - name: Retrieve last entry and send to Lambda
      env:
        LAMBDA_FUNCTION_URL: ${{ secrets.LAMBDA_FUNCTION_URL }}
        LAMBDA_FUNCTION_API_KEY: ${{ secrets.LAMBDA_FUNCTION_API_KEY }}
      run: |
        import json
        import requests

        with open('last_entry.json') as f:
            last_entry = json.load(f)

        if not last_entry:
            print("No valid last entry found.")
            sys.exit(1)

        name = last_entry.get('name', '')
        email = last_entry.get('email', '')

        response = requests.post(
            url=${{ secrets.LAMBDA_FUNCTION_URL }},
            headers={
                "Content-Type": "application/json",
                "x-api-key": ${{ secrets.LAMBDA_FUNCTION_API_KEY }}
            },
            json={
                "userName": name,
                "email": email
            }
        )
        print(response.status_code, response.text)
